import { CHANNELS, MEDIA_ITEMS, UNIQUE_MEDIA, type GuidedState } from '@/lib/demo-state';
import { Panel, Badge, Note, s } from './DemoUi';

function Facts({ rows }: { rows: string[][] }) {
  return <dl className={s.facts}>{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;
}
export default function GuidedScene({ state: g }: { state: GuidedState }) {
  const { stage, evidence: e } = g;
  if (g.slug === 'lead-operations') {
    if (stage === 0) return <Panel title="Maya · website visitor"><div className={s.chatUser}>What documents do I need, and when is the next intake?</div><Note>The assistant will use the team’s approved programme information.</Note></Panel>;
    if (stage === 1) return <Panel title="Answer for Maya"><div className={s.chatAnswer}><p>You will need academic transcripts, identification and English-language evidence. The next listed intake is September 2026.</p><p>An adviser can confirm your individual requirements.</p></div><Badge>Based on the admissions documents and programme intake guide</Badge></Panel>;
    if (stage === 2) return <Panel title="Maya’s callback request"><Facts rows={[["Name",e.name],["Email",e.email],["Request","Please ask an adviser to call me."]]}/><Note tone="good">Maya agreed to be contacted about this enquiry in the fictional scenario. You are not submitting your own details.</Note></Panel>;
    if (stage === 3) return <Panel title="Priya · assigned adviser"><Badge>Customer enquiry saved and assigned</Badge><h4>Reply for your review</h4><blockquote className={s.quote}>{e.reply}</blockquote><Note>Review this message before the callback can be scheduled.</Note></Panel>;
    return <Panel title={stage === 5 ? 'Callback confirmation' : 'Ready for the callback'}><Badge tone="good">Reply approved by Priya</Badge><Facts rows={[["Customer",e.name],["Responsible person","Priya · admissions adviser"],["Callback","10 Sep 2026 · 14:30 SLST"]]}/><p>{e.reply}</p><Note tone="good">{stage === 5 ? 'Callback recorded in this demo. No email was sent.' : 'The approved reply and named adviser stay attached to this enquiry.'}</Note></Panel>;
  }
  if (g.slug === 'campaign-operations') {
    if (stage === 0) return <Panel title="October Open Day"><div className={s.creative}><span>24 OCTOBER / OPEN DAY</span><h4>Your next chapter starts here.</h4><p>Explore programmes. Meet the team.</p></div><Facts rows={[["Confirmed event date","24 October 2026"],["Application deadline","Not provided"],["Channels","LinkedIn, Instagram and X"]]}/></Panel>;
    if (stage === 1) return <Panel title="Draft social post"><Badge>Draft · not approved</Badge><blockquote className={s.quote}>Explore our October Open Day. Applications close 30 September.</blockquote><Note>The next action compares the draft with the confirmed event details.</Note></Panel>;
    if (stage === 2) return <div className={s.twoColumn}><Panel title="What needs correcting"><Note tone="warn">“Applications close 30 September”</Note><p>The event brief does not support this deadline.</p></Panel><Panel title="Proposed replacement"><Note tone="good">“Ask about current application dates.”</Note><p>Keep the confirmed event date: 24 October.</p></Panel></div>;
    if (stage === 3) return <div className={s.stack}>{CHANNELS.map(c => <Panel key={c} title={c}><p>{e.copies[c]}</p></Panel>)}</div>;
    if (stage === 4) return <Panel title="Approved posts · ready to schedule"><Badge tone="good">Alex approved all three posts</Badge><Facts rows={[["Publishing time","18 Oct 2026 · 09:00 SLST"],["Channels","LinkedIn, Instagram and X"],["Rule","Publish only the saved, approved posts"]]}/><p>No further changes are included in this run.</p></Panel>;
    return <Panel title="Publishing confirmation"><Badge>Simulation only</Badge>{CHANNELS.map(c => <Note key={c} tone="good">{c} · approved post delivered in the simulation</Note>)}<p>These are sample delivery confirmations, not measured performance.</p></Panel>;
  }
  if (g.slug === 'operator-workstation') {
    if (stage === 0) return <Panel title="Project Atlas"><div className={s.command}><div className={s.orb} aria-hidden/><div><h4>Check the project and tell me what needs attention.</h4><p>Read first. Do not make changes yet.</p></div></div><Badge>Project owner’s prepared request</Badge></Panel>;
    if (stage === 1) return <Panel title="One form issue found"><Facts rows={[["Answer entered","Three spaces, with no visible text"],["Current behaviour","The form accepts the answer"],["Expected behaviour","Ask the customer to enter an answer"]]}/><Note tone="warn">A blank-looking answer should not be accepted as complete.</Note></Panel>;
    if (stage === 2 || stage === 3) return <Panel title={stage === 2 ? 'Proposed fix and boundaries' : 'Approved fix and boundaries'}><Badge tone={stage === 3 ? 'good' : 'neutral'}>{stage === 3 ? 'You approved this plan' : 'Waiting for your approval'}</Badge><h4>Reject blank answers and add a check.</h4><Facts rows={[["Allowed","Prepare the fix and its check in two project files"],["Not allowed","Deployment, external messages or unrelated changes"],["After the run","A person reviews the prepared changes"]]}/></Panel>;
    if (stage === 4) return <Panel title="Simulated check result"><Note tone="good">An answer containing only spaces is now rejected.</Note><Facts rows={[["Before","One check failed"],["After","All 42 focused checks pass in the simulation"]]}/><p>The change still needs a person’s review before release.</p></Panel>;
    return <Panel title="Handover to the Atlas project owner"><Badge tone="good">Ready for human review</Badge><Facts rows={[["Prepared","Form fix and a check in two files"],["Checks","42 focused checks pass in the simulation"],["Next action","Review the changes and run the complete checks before release"]]}/><Note>No real project files were changed. Nothing was deployed.</Note></Panel>;
  }
  if (stage === 0) return <Panel title="Regional logistics policy"><div className={s.stats}><div><strong>8</strong><span>source items</span></div><div><strong>6</strong><span>articles</span></div><div><strong>2</strong><span>videos</span></div></div><p>The team needs a short brief on what changed and what still needs confirmation.</p></Panel>;
  if (stage === 1) return <Panel title="Coverage after grouping"><Facts rows={[["Captured","8 articles and videos"],["Repeated coverage","3 items linked to their originals"],["Distinct reports",String(UNIQUE_MEDIA.length)],["Needs review","1 disagreement about the start date"]]}/><Note>Repeating a claim does not independently confirm it.</Note></Panel>;
  if (stage === 2) return <div className={s.twoColumn}><Panel title="Coastline News · video"><blockquote className={s.quote}>The presenter describes an immediate effective date.</blockquote></Panel><Panel title="Regional Policy Office · notice"><blockquote className={s.quote}>The effective date will be confirmed in a separate notice.</blockquote></Panel></div>;
  return <Panel title={stage === 5 ? 'Approved policy brief' : stage === 4 ? 'Brief ready for your approval' : 'Draft policy brief'}><Badge tone={stage === 5 ? 'good' : 'neutral'}>{stage === 5 ? 'Sam approved with the date unconfirmed' : 'Not approved yet'}</Badge><p>Eight captured items form five distinct reports. One disagrees on when the policy takes effect.</p><Note tone="warn"><h4>The start date is unconfirmed.</h4><p>Coastline News describes an immediate date, but the Regional Policy Office says a separate notice will confirm it.</p></Note><p>Sources: Coastline News and Regional Policy Office.</p>{stage === 5 && <Facts rows={[["Reviewer","Sam · research team"],["Next action","Monitor the Policy Office for a dated notice"]]}/>}</Panel>;
}

export function SupportingDetails({ state: g }: { state: GuidedState }) {
  if (g.status !== 'complete') return null;
  const e = g.evidence;
  return <div className={s.stack}><Badge>Fictional evidence · read-only</Badge>
    {g.slug === 'lead-operations' && <><h3>Approved references</h3><p>Admissions documents: academic transcripts, identification and English-language evidence. An adviser confirms individual requirements.</p><p>Programme intakes: September 2026 is listed. Availability and eligibility require adviser confirmation.</p><p>Reference owner: admissions team · reviewed 08 Sep 2026.</p><h3>Handoff history</h3><p>Maya requested contact → enquiry saved → assigned to Priya → reply approved → callback scheduled for 10 Sep 2026, 14:30 SLST.</p><blockquote className={s.quote}>{e.reply}</blockquote></>}
    {g.slug === 'campaign-operations' && <><h3>Approved brief</h3><p>Open Day: 24 October 2026. Explore programmes and meet the team. No application deadline or guaranteed outcome is supported.</p>{CHANNELS.map(c => <section key={c}><h4>{c}</h4><p>{e.copies[c]}</p></section>)}<h3>Approved version fingerprint</h3><code className={s.code}>{e.digest}</code><p>The browser computed this SHA-256 fingerprint over all channel copy, artwork version, event date and publishing time.</p><h3>Publishing history</h3><p>Alex approved the saved posts → scheduled for 18 Oct 2026, 09:00 SLST → three simulated deliveries confirmed.</p><h3>Fictional example report</h3><p>These sample interactions illustrate reporting. They are not client results or measured performance.</p><table className={s.table}><thead><tr><th>Channel</th><th>Reactions</th><th>Questions</th></tr></thead><tbody>{CHANNELS.map((c,i)=><tr key={c}><th>{c}</th><td>{[24,38,12][i]}</td><td>{[4,6,2][i]}</td></tr>)}</tbody></table></>}
    {g.slug === 'operator-workstation' && <><h3>Permission record</h3><p>The operator approved preparing a validation fix and regression check. External messages, deployment and unrelated changes were not permitted.</p><h3>Prepared file comparison</h3><pre className={s.code}>{'src/validation.ts\n- return value.length > 0;\n+ return value.trim().length > 0;\n\ntests/validation.test.ts\n+ expect(isValid("   ")).toBe(false);'}</pre><h3>Simulated test evidence</h3><p>Baseline: 41 passed, 1 failed. After the prepared fix: 42 passed, 0 failed.</p><h3>Saved follow-up</h3><p>Atlas project owner · due 11 Sep 2026. Review the changes and run the full checks before release. This is a tab-local demo record, not a real task assignment.</p></>}
    {g.slug === 'media-intelligence' && <article className={s.report}><h3>Approved policy report</h3><p>{e.summary}</p><Note tone="warn">Known uncertainty: the start date remains unconfirmed. Monitor the Policy Office for a dated notice.</Note><p>Reviewer: Sam · 10 Sep 2026.</p><h3>Sources used</h3>{MEDIA_ITEMS.map(x=><section key={x.id}><h4>{x.name} [{x.id}]</h4><p>{x.claim}</p><p>{x.duplicateOf ? `Repeated coverage linked to ${x.duplicateOf}.` : 'Representative report.'} {x.type === 'Video' ? 'Prepared video excerpt, 01:12–01:34.' : 'Prepared article excerpt.'}</p></section>)}<h3>Processing history</h3><p>8 items captured → 3 repeats linked → 5 distinct reports compared → 1 disagreement retained → summary reviewed and approved.</p><button type="button" className={s.secondary} onClick={()=>window.print()}>Print report</button></article>}
  </div>;
}
